### ISSUE TITLE
GetTypeLink fails for tuples

### ISSUE THREAD

**Issue by phil-scott-78** [statiqdev/Statiq.Docs#47]
I think there needs to be a special case. Once it gets into the `if (typeArguments?.Count > 0)` branch this succeeds, but then it fails with a "count can't be negative" error because the display name is something like `(string Left, string Center, string Separator, string Right)` after looking for the `<` and `>` in the type name rather than `Tuple<string, string, string, string>`

**Comment by daveaglick** [comment]
Great find - it wouldn't surprise me if there were other tuple problems as well given the slightly unusual syntax. I'll need to go through and audit this stuff for the newer language constructs since it was ported from Wyam and predates some of it.

**Comment by daveaglick** [comment]
Going to move this to Statiq Docs since this functionality is provided there and not in the theme

**Comment by daveaglick** [comment]
This is now fixed and I'll do a release tomorrow to get it out. Thanks for reporting!

**Comment by deap82** [comment]
@daveaglick I'm still getting this error when trying to generate docs from C# XML documentation comments. I tried to uninstall and then install the Statiq.Docs nuget package (using Visual Studio UI), but it did not help. Perhaps there is something I'm not aware of when it comes to ensuring the latest version of a nuget package even though the version number didn't change in your latest release...(?) The latest version I'm seeing is 1.0.0-beta.2 and that's the same as I had before.

One code piece that seems to cause the issue looks like this;

```
public (bool passwordChange, bool userNameChange, bool emailChange) UserChangeCredentialsAllowed(string userid, bool userIsStaff)
{
    return (true, true, true);
}
```

**Comment by daveaglick** [comment]
Well nuts. This looks like a release issue on my end. I somehow ended up with the same version number - so while the release seemed like it worked from my build tooling, NuGet rejected it for having the same version number.

The good news is this should be an easy thing to resolve. I'll bump it properly and get a new version out this afternoon. I'll come back here once I've verified the correct version is up on NuGet. Sorry for the confusion!

**Comment by daveaglick** [comment]
Statiq Docs 1.0.0-beta.3 out on NuGet now
